import { ReactNode } from "react";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google"; // Updated to import DM Sans
import "../globals.css";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import dynamic from "next/dynamic";
import Loader from "./components/loader/page";


// Dynamically import components to optimize performance
const ComponentLayout = dynamic(() => import("./components/layout"), {
  // loading: () => <div>Loading Layout...</div>,
  ssr: false, // Set to false to disable server-side rendering for this component
});
const ToastProvider = dynamic(() => import("./components/toastProvider/page"), {
  // loading: () => <Loader/>,
  ssr: false,
});

const dmSans = DM_Sans({ subsets: ["latin"] });

interface LayoutProps {
  children: ReactNode;
  params: { locale: string };
}

export const metadata: Metadata = {
  title: "ADURE - Real Estate and Property Management Company in Abu Dhabi",
  description: "Generated by create next app",
};

const Layout: React.FC<LayoutProps> = async ({
  children,
  params: { locale },
}) => {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body
        className={`${dmSans.className} banner overflow-hidden overflow-y-auto`}
      >
        <NextIntlClientProvider messages={messages}>
          <ComponentLayout>
            <ToastProvider>{children}</ToastProvider>
          </ComponentLayout>
        </NextIntlClientProvider>
      </body>
    </html>
  );
};
export default Layout;
